### ISSUE TITLE
Story text is appearing in wrong order

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/intertwine#102]
Two of the stories have paragraphs that are displayed in the wrong order.

## Cabernet
The second paragraph should be first. 

Cabernet story: https://intert-wine-leigh-akwemh35fa-uc.a.run.app/story/cabernet 

![Screen Shot 2020-12-03 at 2 37 16 PM](https://user-images.githubusercontent.com/17831969/101096908-1da91c80-3575-11eb-8d14-ea527a288ca2.png)

Trello card: https://trello.com/c/DvutblIw/169-cabernet-comes-to-california

![Screen Shot 2020-12-03 at 2 38 38 PM](https://user-images.githubusercontent.com/17831969/101096999-3dd8db80-3575-11eb-8e1e-06ab13cf9917.png)

## Chardonnay
There are multiple sections with out of order text in this story. 

[Intertwine App Chardonnay Story](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/story/chardonnay)

Modest Beginnings -- [trello](https://trello.com/c/8NXCOJyg/108-modest-beginnings) 
Chardonnay Comes to California -- [trello](https://trello.com/c/hfVKhXmn/110-chardonnay-comes-to-california)
Chardonnay's Rise -- [trello](https://trello.com/c/VQXiakyP/113-chardonnays-rise)

**Comment by jrmerz** [comment]
@qjhart This one looks to be a data issue.  Story text arrays for paragraphs are coming in in the order displayed on screen in the app.

**Comment by qjhart** [comment]
@jrmerz since AFAIK, there is now markdown would you object to a single text field where the paragraphs are separated by "\n"

**Comment by jrmerz** [comment]
I have no problem with this.  a 'List' structure seems like possibly a little over kill for this anyway (IMHO).

**Comment by wrenaria** [comment]
It's only currently in a list structure because that's what Leigh wanted at the time.

**Comment by qjhart** [comment]
@jrmerz text merge at https://github.com/ucd-library/trello2moment/pull/56
