### ISSUE TITLE
Connection Label and Arrowhead persists after clicking away

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/intertwine#106]
Connection label and arrowhead are getting stuck and persisting even after clicking on map items or changing to a new map.

For example, I opening a connection on Chardonnay map, went to the homepage, then opened the Cabernet map to see this:

![Screen Shot 2020-12-04 at 9 27 52 AM](https://user-images.githubusercontent.com/17831969/101194657-22241280-3613-11eb-8216-3a46090141d6.png)

Even within the same map, the last displayed connection label and arrow persist until you open a new connection.

**Comment by jrmerz** [comment]
This is tied to badness causing delays in #68 ... Did best to fix, but let me know if fix broke something else.  My playing around it seems ok....

**Comment by wrenaria** [comment]
Looks like it's working fine now!
