### ISSUE TITLE
Map panel: Connections are showing incorrectly

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/intertwine#25]
Connections are showing incorrectly and need to be fixed. I'll use Mike as an example to explain how connections are supposed to implemented.

![Screen Shot 2020-02-27 at 12 03 06 PM](https://user-images.githubusercontent.com/17831969/75482347-81087d00-5959-11ea-91bb-378bd3573a25.png)

Connections should show the connection word + subject, nothing else. So his connections should be:

- _winemaker_ 1973 Chateau Montelena Chardonnay
- _mentored by_ André Tchelistcheff

The dot color should also reflect the linked subject, so in this case, André's dot stays red (person), but 1973 Chateau Montelena Chardonnay's dot should be purple (object).

If we were to then go look at the subject page for one of Mike's connected subjects -- in this case, André, his connection to Mike would read:

- _mentored_ Mike Grgich

The subject order is always **selected subject → connection word → connected subject** with the selected subject not displayed in the connection text and the connecting word changing form depending on which subject is the selected one. There is a base and reverse form for every connection word. 

I'm going to take this explanation a step further to ensure understanding of how this is working from the data side. Let's look at the trello card for André and Mike's connection:

![Screen Shot 2020-02-27 at 12 30 57 PM](https://user-images.githubusercontent.com/17831969/75484256-4274c180-595d-11ea-9734-6710bf937949.png)

In the trello cards, connections have a specific order and that is how you determine which word to show. The first card is the starting point and uses the first word in the connection label (mentored/mentored by).

Andre → Mike
Andre _mentored_ Mike

If you reverse it and read the cards backward, you use the second form on the connection word to connect them.

Andre ← Mike
Mike _mentored by_ André

But since the starting subject's card already contains their name and info, we don't need it to repeat in the connections list on the map subject panel and it gets dropped in that context.

**Comment by ldragoon** [comment]
@qjhart @wrenaria - I think this fix will have to become part of Trello2Moment, because the current JOP data comes over looking like this:

![image](https://user-images.githubusercontent.com/7807437/76886912-aee92f00-683e-11ea-9a85-ffb2e29b3acb.png)
