### ISSUE TITLE
Map Connection Cluster Panels: Style Adjustments Needed

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/intertwine#26]
Feature image styling is currently incorrect on Connection panels.

Screenshot from current application:

![Screen Shot 2020-02-27 at 4 23 06 PM](https://user-images.githubusercontent.com/17831969/75498980-7e1f8380-597d-11ea-9f58-45f0466c6935.png)

**Items to fix:**
- [x] Replace blue icon in the feature image spot of the cluster panel with the colored version, found here: https://drive.google.com/open?id=1VOQWWTAgUCkMzc-khMNye9CTdbkzHJq8
- [x] Cluster Icon should be 100px.
- [x] Feature image box would have 150px height.
- [x] "Select a Subject" should be H1, not H3
- [x] Need more space between list items to make items easier to click on mobile devices -- they are currently too close together. See mock-up below.

Mock-up of correct styling:

![Screen Shot 2020-02-27 at 4 22 08 PM](https://user-images.githubusercontent.com/17831969/75498909-56302000-597d-11ea-8e32-15cae805e8c1.png)

**Comment by wrenaria** [comment]
Three things:

- [x] The feature image box is wrong height -- should be 150px not 200px.

- [x] "Select a Subject" should **not** have extra margin above it when it's the first item on the panel or it will appear too low down. 
![marginerror](https://user-images.githubusercontent.com/17831969/76125984-d1638880-5fb2-11ea-8a07-4c94e162cfff.png)

- [x] Category titles need to be middle-aligned on icon circles. Currently, they are not.
<img src="https://user-images.githubusercontent.com/17831969/76126642-7b8fe000-5fb4-11ea-8a88-b64f0d4ebcc1.png" width="270">

**Comment by wrenaria** [comment]
Somehow the text in the connection lists are no longer aligned correctly (it was correct in the past). The text (category headers + subjects) should align all the way down the list.

## Current Site:

![Screen Shot 2020-09-17 at 12 14 13 PM](https://user-images.githubusercontent.com/17831969/93516741-53782680-f8df-11ea-9ed2-32ca29167a94.png)


## Correct / As designed:

![image](https://user-images.githubusercontent.com/17831969/93516653-32afd100-f8df-11ea-9c44-ee68755be6e1.png)

**Comment by wrenaria** [comment]
It looks like the styles for bullets got changed on Subject panels too, which is not what I wanted. These changes were only meant for Cluster panels. So now it is correct on clusters and incorrect on subjects!

**Comment by wrenaria** [comment]
If an item's title is long enough to break into multiple limes, this style fix did not extend to any line below the first one.

![Screen Shot 2020-09-30 at 3 09 21 PM](https://user-images.githubusercontent.com/17831969/94745291-43286880-032f-11eb-8419-555d01142fdb.png)

Text to needs to align all the way down, regardless of how many lines it takes up.

**Comment by wrenaria** [comment]
Nothing has changed since my last comment. Titles that take up multiple lines are still aligned incorrectly. Here are examples of current (incorrect) alignment.

**Example 1:**
![Screen Shot 2020-10-01 at 3 22 40 PM](https://user-images.githubusercontent.com/17831969/94869467-3cb2f300-03fa-11eb-99d9-461a050764e8.png)

**Example 2:**
![Screen Shot 2020-10-01 at 3 18 56 PM](https://user-images.githubusercontent.com/17831969/94869202-b8607000-03f9-11eb-92f8-46f4aa39e1d4.png)

The text needs to align/be padded consistently all the way down, no matter the number of breaks in a title. Unrealistic example, but if a title required 10 lines to display, it should all still appear consistently aligned with the beginning of first line.

Example above is a screenshot from this url viewed at both Mobile sizes via dev tools and on my actual phone: 
https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/chardonnay/cluster/38.1131,-122.1616/3

**Comment by jrmerz** [comment]
@wrenaria should be fixed on dev now

**Comment by wrenaria** [comment]
@jrmerz, Sorry closed this too soon. Text needs to have the same alignment all the way down, including to the other "bulleted" lists of content.

![alignment](https://user-images.githubusercontent.com/17831969/100924907-1e1eb600-3496-11eb-8963-9347c0f83517.png)

This change should only affect subject panels. Cluster panels look perfect as is. (Clusters and single subject panels have different spacing rules.)

**Comment by jrmerz** [comment]
@wrenaria can you point me at this? ```Clusters and single subject panels have different spacing rules```

**Comment by wrenaria** [comment]
@jrmerz Original style guide -- https://drive.google.com/drive/u/1/folders/17IWlzD3E4EPS5YTh5QxKgxRW0eZu_tlS

At its heart, the rules are the same for all panels: text aligns to other text all the way down.

But on subject info panels, there should be less space between dot/icon and text than on a cluster (clusters have larger icon imagery to accommodate). What I forgot to say explicitly in my screenshot comment: the "learn more" text placement is correct, but the connection text is too far to the right.

**Comment by wrenaria** [comment]
@jrmerz And of course after I comment, I see your fix, haha, and it looks good. Closing issue.
