### ISSUE TITLE
Selected connection lines need arrowheads to show connection direction

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/intertwine#37]
All connections have a base direction. There should ideally be an arrowhead at the end of the connection line to indicate the connection direction.

Example from design spec sheet:

![Screen Shot 2020-03-06 at 2 40 10 PM](https://user-images.githubusercontent.com/17831969/76128164-6c129600-5fb8-11ea-8d84-17085da9bd5b.png)

Example of why this is helpful:

![Screen Shot 2020-03-06 at 2 37 28 PM](https://user-images.githubusercontent.com/17831969/76128184-7765c180-5fb8-11ea-8b83-7c1f740616d4.png)

Who mentored who? The arrow would show that at a glance.

**Comment by ldragoon** [comment]
![image](https://user-images.githubusercontent.com/7807437/88333087-78d42400-cce4-11ea-9509-c3e1963ca53a.png)

The arrow needs to switch direction to match the currently selected Card.

Pertinent Code

1. app-leaflet-map.js

**Comment by wrenaria** [comment]
It doesn't, actually. You only need to show one direction and always use the base connection word (the left side word on the Trello label) and direction for that connection. The example you posted should be "Moris - owned - Hedgeside" and it consistently stays as that no matter which card is selected.

**Comment by ldragoon** [comment]
So basically this is done, and I don't have to do anything? :D

**Comment by wrenaria** [comment]
The example screenshot you posted above is showing the wrong connection word. it should just be "owned," since Morris is not owned by his vineyard. [Trello source](https://trello.com/c/buqHYhc6/148-morris-estee-owned-hedgeside-vineyards):

![Screen Shot 2020-07-23 at 1 43 52 PM](https://user-images.githubusercontent.com/17831969/88336851-8ee4e300-ccea-11ea-85b4-e18ad08bac3d.png)

**Comment by ldragoon** [comment]
Thank you! This clarifies things so much! Diving back in. :D
