### ISSUE TITLE
Return to Top of Previous Page

### ISSUE THREAD

**Issue by ldragoon** [ucd-library/intertwine#45]
When a user navigates away from a page, when they return to the previous pages, the cursor should return to the top of the page.

**Comment by ldragoon** [comment]
Added code to perform this on line 52 of app-story.js

```
/**
   * @method _onAppStateUpdate
   * @description bound to AppStateModel app-state-update events
   *
   * @param {Object} e
   */
  async _onAppStateUpdate(e) {
    this.container.scrollTo(0,0); // return to top of page
```

**Comment by wrenaria** [comment]
Going back to the Homepage from anywhere else does not load it from the top if you were scrolled down when you left it (but it should).
