### ISSUE TITLE
Trello Data Either Missing or Displaying Incorrectly

### ISSUE THREAD

**Issue by ldragoon** [ucd-library/intertwine#63]
- [x] Order of Story Triptych items incorrect

- [ ] Missing Data:

- [x] Andres Tchelistcheff - missing his connections

	https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/jop/person/uPuH2QQJ

- [ ] Joanne DePuy - She should also have connections

	https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/jop/person/HDmnuCC5

**Comment by wrenaria** [comment]
Here's direct links to the Trello data as well, in case it helps.

André: https://trello.com/c/uPuH2QQJ/97-andr%C3%A9-tchelistcheff

Joanne: https://trello.com/c/HDmnuCC5/91-joanne-depuy

**Comment by jrmerz** [comment]
From @ldragoon `Displays one of her two connections but I'm having trouble figuring out why the second one is not displaying`.  

Inspecting the graph, client side, I only see one link `2BX91onm - Joanne DePuy delivered wine to Steven Spurrier`.   Going to say this is a data issue. @qjhart I'm going put you on this. There is a branch for this issue: https://github.com/ucd-library/intertwine/tree/issue-63-depuy-missing-connection

**Comment by qjhart** [comment]
@ldragoon the fix, https://github.com/ucd-library/trello2moment/pull/52 should address this, we are still waiting on you to finalize the previous PR there however.
