### ISSUE TITLE
Intertwine - Moments not Loading Initially on GCloud

### ISSUE THREAD

**Issue by ldragoon** [ucd-library/intertwine#64]
When first going to google cloud instance, app does not load moments until screen refreshed.

intert-wine-leigh-akwemh35fa-uc.a.run.app

**Comment by jrmerz** [comment]
You are not waiting for the moments to load (https://github.com/ucd-library/intertwine/blob/dev/controllers/static.js#L43) , so on first load of the app, the moments array is null in APP_CONFIG.
