### ISSUE TITLE
Maps - Requested Feature - Additional Label Mouseover Functionality

### ISSUE THREAD

**Issue by ldragoon** [ucd-library/intertwine#68]
**Maps**
- [ ] When mouse over connection on side bar. Is it possible for the connection line and label to light up on the map.

Ask Justin - sometimes when the label is clicked the map view changes - map view should only be changed by user making direct action on the map itself not the sidebar.

**Comment by wrenaria** [comment]
@jrmerz This looks great except the name at the other end of the connection should show up too, not just the blue connection line/word.
