### ISSUE TITLE
Verify the new format is workable

### ISSUE THREAD

**Issue by qjhart** [ucd-library/intertwine#7]
We have an updated version of the Chardonnay project, in our new format; https://sandbox.dams.library.ucdavis.edu/fcrepo/rest/collection/chardonnay2/chardonnay.json.  This is an amalgamation of all the individual cards in the [chardonnay collection](https://sandbox.dams.library.ucdavis.edu/fcrepo/rest/collection).  We need to verify this is workable for the intertwine project.  

- [x] Test Links
- [x] Verify Nameing
- [ ] Get images

**Comment by ldragoon** [comment]
Example:
Joseph "Joe" Heitz
http://localhost:3000/map/chardonnay/person/CvTHg5Ea

Link address:
https://sandbox.dams.library.ucdavis.edu/fcrepo/rest/collection/moments/chardonnay/CvTHg5Ea/image.png

The link appears to be correct, but so far all the images I've attempted to download directly from fedora show this error:

The file "xxxx.png" could not be opened.
It may be damaged or use a file format that Preview doesn't recognize.

Thumbnail images from the JOP Moment display correctly.

**Comment by wrenaria** [comment]
This seems like an issue @qjhart should close, not me.
