### ISSUE TITLE
Moments (Narrative) UI

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/intertwine#8]
Here is the latest PDF for the Intertwine narrative, containing all design specs for the Moments layout: https://drive.google.com/file/d/14yIllK59ksOk9DF0wYDXHfQh_QxvTtg3/view?usp=sharing

Intertwine assets (icons, pictures) can be found here: https://drive.google.com/drive/u/1/folders/1XkVHUj1gwQXG6GI5XpaXfl6E3ZB6C0nR

Cropped view showing whereabouts the "Explore the Map" sticky button should sit in-browser (see notes in pdf):

![intertWINE - Moment Chardonnay – Cropped](https://user-images.githubusercontent.com/17831969/72113083-4b013200-32f4-11ea-864a-16f9cc4ab705.jpg)

See pdf for full view of content.

**Comment by ldragoon** [comment]
I have a completed Chardonnay example that has all the data hardcoded into it.

**Comment by wrenaria** [comment]
@ldragoon -- Here are the story layout adjustments that need made:

## Feature image
- [x] This image needs to grow and shrink at a consistent, constrained ratio (the same way images do on the homepage cards -- use same ratio).

## "Explore the Map" Tag
- [x] It is the wrong color, but I seeing it in-browser has changed my mind on the color entirely anyway. Let's make it #333333 / charcoal.
- [x] The shadow is too heavy; drop to from .75 to .3
- [x] The tag should extend all the way to the edge of the browser, no separation at right edge.
- [x] The chevron should be the iron icon "chevron-right", not text-based. 

Should look something like this:
![Screen Shot 2020-02-25 at 4 13 22 PM](https://user-images.githubusercontent.com/17831969/75300281-39b0ae00-57ec-11ea-9564-4c95d0816950.png)

## Blue Title/Quote Area
- [x] Quote source should be regular text, not italic 
- [x] Remove 5px above "Growth of Chard" title
- [x] Add 10 px between quote and title

How it should look after changes:
![Screen Shot 2020-02-25 at 3 54 27 PM](https://user-images.githubusercontent.com/17831969/75298365-251de700-57e7-11ea-8993-b34ca31909a1.png)

## Grey Text Areas
- [x] Text margin should stay consistent on the side closest to the center line instead of text moving away it on larger screen sizes. Does that make sense? If not, ping me. Screenshot examples:

Always like this:
![Screen Shot 2020-02-25 at 3 44 09 PM](https://user-images.githubusercontent.com/17831969/75298683-053af300-57e8-11ea-9c06-802a3a23600d.png)
![Screen Shot 2020-02-25 at 4 01 38 PM](https://user-images.githubusercontent.com/17831969/75298741-2996cf80-57e8-11ea-9a7f-cc713ba214cb.png)

Never like this:
![Screen Shot 2020-02-25 at 3 44 15 PM](https://user-images.githubusercontent.com/17831969/75298657-f3595000-57e7-11ea-9769-4e466305b557.png)
![Screen Shot 2020-02-25 at 4 01 54 PM](https://user-images.githubusercontent.com/17831969/75298748-2c91c000-57e8-11ea-9beb-fe888766e0e2.png)

## 3 Set images
- [x] These need to have constrained, consistent ratios when resizing (just like homepage cards and story feature image -- use same ratio) otherwise you lose too much image at larger scales, as you can see here:

![Screen Shot 2020-02-25 at 3 29 55 PM](https://user-images.githubusercontent.com/17831969/75299311-9363a900-57e9-11ea-944d-76d71f24df57.png)

## Blue "Explore" Section
- [x] Text sizing and spacing needs to be the same as the rest of the page -- Growth of Chardonnay header is the wrong size and things are incorrectly spaced. Take a look at my mockups again.
- [x] At large sizes, the center line shifts and doesn't match the previous set of content boxes. This is not desirable.

![Screen Shot 2020-02-25 at 4 08 31 PM](https://user-images.githubusercontent.com/17831969/75299119-19332480-57e9-11ea-976f-277880f8a042.png)

## Footer
- [x] I changed my mind on the text color. it seems brighter in-browser than in my design program. Let's try #767676 / stone -- a new color added via issue #31

**Comment by wrenaria** [comment]
Looks like you missed my feedback comment above. Plenty that needs fixed here still.

**Comment by wrenaria** [comment]
Things that need fixed:

- [x] Quote in blue title area is still wrong -- Quote should be italic, source is normal text. 
- [x] Caption text size should be 13px; padding: 5px 10px; background opacity 0.65
- [x] The Image triptychs are supposed to be a similar ratio as feature image at top. That means the padding-top needs to be around 18.5% (because each image is 33% width).
- [x] Text width: Even though my mock-up had 750px max width for text, looking at it in-browser I think we need to drop it to 550px max width because at the higher number we're well above recommended characters in a line for readability. 
- [ ] What happened to max width on text in the gray and blue text sections? It needs to be there as it's a critical component for readability. I just want the text box to hug the middle of the page and not the outside edges of the browser, if that makes sense and is possible.
