### ISSUE TITLE
DAM - Integration

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/intertwine#88]
We have been writing our client to look at moments.dams.library.ucdavis.edu.  The goal is for these to be pubished to regular dams.  
1) Does it make sense to have in one collection?
2) Is it easy to spread these around collection.
3) For example, a moment about boy scout troup has is in the boy scout collection.  Have to include trello2moment setup. OR simplified version moment

**Comment by jrmerz** [comment]
@qjhart would you consider this required for public release?

**Comment by qjhart** [comment]
@jrmerz, No.  The trello2moment command should create a single directory of content for a moment, and all the references within that directory are relative.  There is currently no requirement that data be made available via the DAMS, and the DAMS metadata services are not used to power a moment, so you could as easily simply run `trello2moment` in any web accessable location.

**Comment by jrmerz** [comment]
Ok, I'm removing the issue from the first public release project board then.
