### ISSUE TITLE
Intertwine-deployment repository required?

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/intertwine#89]
from Quinn: Is intertwine setup, complex enough to require it's own deployment.  Does this have it's own dockerfile w/ the client interface?

**Comment by jrmerz** [comment]
@qjhart Interwine, the application, is a single NodeJS server deployed to Google Cloud Run using Docker.  Obviously the DAMS is a 'deployment' docker cluster.  The only part of this app I'm not sure how to answer is trello-to-moment.  Is that a tool that should be part of some CI pipe?

But I think I can safely say that no, Interwine does not require a full deployment repo and the deployment can and should be easily captured in this repository, as it currently is.

**Comment by qjhart** [comment]
As discussed in #88, a bit, the use of trello2moment is somewhat dependant on the destination of the moments, and would affect I guess the decision of whether to build an image for the trello2moment command.
