### ISSUE TITLE
Homepage UI

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/intertwine#9]
Here is the latest PDF for the Intertwine homepage, containing all design specs for the homepage layout: https://drive.google.com/file/d/1PXvTEtiOx9Tp1o62JxvYCw39JRI1WCTO/view

Intertwine assets (icons, pictures) can be found here: https://drive.google.com/drive/u/1/folders/1XkVHUj1gwQXG6GI5XpaXfl6E3ZB6C0nR

![IntertWine - HomePage-2](https://user-images.githubusercontent.com/17831969/72113739-2efe9000-32f6-11ea-89fc-8bff3000217f.png)

See pdf for how components break for smaller screens.

**Comment by ldragoon** [comment]
@wrenaria - I need to update the app so the homepage is the default view served, but you can use this to take a look at the layout:

https://intert-wine-leigh-akwemh35fa-uc.a.run.app/home

**Comment by wrenaria** [comment]
It's on it's way! A few things...

- [x]  The connected icons header image should be centered in the blue header area and never change size. It will get cropped in various ways depending on screen size and that is fine. There should be no need for blue blocks behind the text because it's designed to never overlap that area.

- [x]  Overall card heights should be the same

- [x]  I'd like the feature image ratio on the cards to grow and shrink at the same ratio no matter the size of the card.

- [x]  The space between card title and date feels too tight to me, increase it a little.

- [x]  Links need a mouseover color -- use #015E80 / secondary-blue -- use this as mouseover color on the text links and the UCD library logo background in the header.

- [x]  The space under the blue down arrow is too tight. Increase to be 50px, not 32. Like so:

![Screen Shot 2020-02-19 at 12 16 04 PM](https://user-images.githubusercontent.com/17831969/74872212-ae2dad80-5311-11ea-9921-03df468a58a5.png)

**Comment by ldragoon** [comment]
@wrenaria - Go ahead and take another look. :)

**Comment by wrenaria** [comment]
- [x] Header image size is good, but the blue part still needs to be dynamic, so even though the image stays the same size and centered, the blue background stretches based on content. Otherwise you get this: 

![Screen Shot 2020-02-20 at 1 48 59 PM](https://user-images.githubusercontent.com/17831969/74982171-78a7c380-53e8-11ea-95f2-651263806c22.png)
----

- [x] Cards need to be same height, no matter the content. The white part on 2nd card needs to always stretch down to match the longest card.

![Inter-Cards](https://user-images.githubusercontent.com/17831969/74982829-ac371d80-53e9-11ea-8daa-337d510d5d76.png)
----

- [x] The feature image ratio on the cards to grow and shrink at the same ratio no matter the size of the card. This is still not correct. I want a 6:3 ratio (actually after messing around with it a 600:350 might be better) no matter the scale. This might mean the image is small on mobile, and that is okay. 

- [x] The space between card title and date feels is too much now lol! Sorry, I should have been more specific. Make the margin 5px instead of 10px, plz!

![Screen Shot 2020-02-20 at 2 32 45 PM](https://user-images.githubusercontent.com/17831969/74986177-e2769c00-53ed-11ea-9b50-7c1423d3d4de.png)
----

- [x] I know I said I wanted this gray line 1px, but I was wrong. Seeing it in browser, I wish it were 2px instead. It is also not aligned correctly, it needs to be centered on the text. It looks like it's positioned about 3-4 px too high. I put a pink highlight on the image below so you can see where the gray line is currently in relation to the text.

![Inter-Alignment](https://user-images.githubusercontent.com/17831969/74986030-9d526a00-53ed-11ea-86f5-08d2b95e3662.png)

That's it for now!

**Comment by ldragoon** [comment]
@wrenaria  - Ok, take another look. :)

**Comment by wrenaria** [comment]
@ldragoon This looks good on desktop, but the header/intro area still needs some refinement at mobile scales.

<img src="https://user-images.githubusercontent.com/17831969/75296549-5f38ba00-57e2-11ea-8e94-1998eab5fe8f.jpg" width="250">

Two problems:
- [x] The intro text is too spread out vertically and needs tightened up
- [x] The header is too cramped. At small scales, the UCD Library logo should drop to just the icon, no wordmark. https://drive.google.com/open?id=1fXJj09cBCBRQsOAsdiYN_J0tcOdNF0wY

Take a look at the last page of the [PDF](https://drive.google.com/file/d/1PXvTEtiOx9Tp1o62JxvYCw39JRI1WCTO/view) from my initial comment for how it should look.

**Comment by wrenaria** [comment]
Text got a little too tightened. Need about 10px more space between header and body on mobile. 

![Screen Shot 2020-03-06 at 10 58 56 AM](https://user-images.githubusercontent.com/17831969/76113783-97d25380-5f99-11ea-8cb1-d5a4fca6a174.png)

Also it looks like the header is getting fatter (from 60 to 80px) at mobile size? Not ideal. If anything it should get smaller. 

In fact, let's change it to 50px height at that smallest break point. Make the blue logo button 50px wide to keep with square with the logo at 37% size. 

![Screen Shot 2020-03-06 at 11 10 17 AM](https://user-images.githubusercontent.com/17831969/76114518-1b407480-5f9b-11ea-8b96-99e6bdadafa5.png)

**Comment by wrenaria** [comment]
Cards do not behave correctly when resizing the viewport.

- The space between two cards should never change. Always 30px. 
- Right now cards are a static size instead of responsive, but this is incorrect behavior. Cards should resize dynamically depending on screen size. Please look at page 3 of the [design pdf](https://drive.google.com/file/d/1PXvTEtiOx9Tp1o62JxvYCw39JRI1WCTO/view) in particular and compare it to the how the site is working now to better understand what I mean. Cards do not break to a single column until the viewport is 859px wide. 

The way things are working at mobile scales right now looks good though. :)

**Comment by wrenaria** [comment]
@jrmerz Two more cleanup items for this round: 
- Since there are two destination options on each card (story or map) the card feature image shouldn't link to anything (currently links to story). 
- The space between the link icons and the separating bar does not appear to be consistent.

![Screen Shot 2020-11-24 at 12 28 39 PM](https://user-images.githubusercontent.com/17831969/100147733-9a8b1680-2e50-11eb-864a-2e5e1c501557.png)

![Screen Shot 2020-11-24 at 12 29 15 PM](https://user-images.githubusercontent.com/17831969/100147781-ae367d00-2e50-11eb-99c9-21983dda92fb.png)
