### ISSUE TITLE
Cabernet Map Data Issues to Fix

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/intertwine#93]
This is a comprehensive list of data/content issues to fix for the [Cabernet map](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/cabernet/). All my testing was done in Chrome. 

**Data missing or incorrectly mapped**:
- [x] Image credit is not displaying at bottom of subject panel (should be, see this [example from Chardonnay map](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/chardonnay/person/ME09Pv74)) 
![Screen Shot 2020-11-30 at 12 24 01 PM](https://user-images.githubusercontent.com/17831969/100660506-fbaa6280-3306-11eb-8e67-ba8d9bb98dcd.png) 
- [x] When I clicked on Maynard Amerine he shows previous selected subject's connections. When I refreshed, his connections vanished. ([map](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/cabernet/person/bspq6IkX), [trello](https://trello.com/c/bspq6IkX/77-maynard-amerine)) -- _Joe Heitz missing was causing this problem, fixed when he was restored to map_
- [x] Martha's Vineayrd has same problem as previous item. ([map](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/cabernet/place/1dSpPRow), [trello](https://trello.com/c/1dSpPRow/44-marthas-vineyard))
- [x] Heitz Cellar, ditto. ([map](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/cabernet/place/q2lHlTcV), [trello](https://trello.com/c/q2lHlTcV/62-heitz-cellar))
- [x] Feature image doesn't load on Louis M. Martini Winery ([map](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/cabernet/place/2BvkysPk), [trello](https://trello.com/c/2BvkysPk/100-louis-m-martini-winery))

**Trello subjects missing from the map**:
- [x] Steven Spurrier ([trello](https://trello.com/c/3kJMLUSG/47-steven-spurrier)) -- _data issue, labels incorrect_
- [x] Joe Heitz ([trello](https://trello.com/c/4OB05MBQ/49-joe-heitz)) -- _data issue, labels incorrect_

**Trello data / image mistakes** (Kimmy will fix):
- [x] Oakville Station Clone has duplicate connections to the same items, need to consolidate ([trello](https://trello.com/c/nRyFlMtg/126-cabernet-sauvignon-fsp-02-oakville-station-clone ))
- [x] Cabernet Sauvignon FSP 02 ("Oakville station") Clone has duplicate connections ([map](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/cabernet/object/nRyFlMtg), [trello](https://trello.com/c/nRyFlMtg/126-cabernet-sauvignon-fsp-02-oakville-station-clone))
- [x] Captain Drummond is headless. ([trello](https://trello.com/c/cgrJ3Yzm/38-captain-james-drummond), [map](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/cabernet/person/cgrJ3Yzm )) 
- [x] Maybe crop HW Crabb better? ([trello](https://trello.com/c/YHlh2fTx/39-hw-crabb ), [map](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/cabernet/person/YHlh2fTx ))
- [x] Stag's Leap trello card is messed up from Mex-Amer board. Need to fix. ([trello](https://trello.com/c/WUqXfCtS/85-stags-leap-wine-cellars))
Make sure these connections are present: 
![Screen Shot 2020-11-30 at 1 09 04 PM](https://user-images.githubusercontent.com/17831969/100666057-40d19300-330d-11eb-8450-6fe35e8e96c6.png)
- [x] Fix Amerine's photo crop

**Comment by wrenaria** [comment]
@qjhart I fixed all the data problems that I could. Take a look at remaining ones and see if we need to assign Justin to this issue.

**Comment by jrmerz** [comment]
data reimported

**Comment by wrenaria** [comment]
Fixing Joe Heitz so that he now appears on the map seems to have solved the vanishing connection problem. All subjects where that was a problem had him as a connection. 

Image credit line seems to still be missing on all subjects on this map. 

Louis M. Martini Winery feature image is missing as well. I'm suspicious it might be because it had a crazy file name? I just renamed it, so maybe it will import correctly now. 

Amerine had a crazy white border on his photo, so I fixed that trello attachment as well.

**Comment by qjhart** [comment]
@jrmerz, it looks like the image credit list items just get added one after the other into the creator field.  Let me know if that makes sense to you, or if it should be differently formatted.

**Comment by jrmerz** [comment]
@qjhart from what I am looking at, image credit link and title come for node creator.  If that's what you are asking?

**Comment by qjhart** [comment]
@jrmerz I wasn't asking, so much  as saying that's what it is, and if you'd prefer a different representation.

**Comment by jrmerz** [comment]
nope, working with what we got is the current guidelines

**Comment by wrenaria** [comment]
I'm going to close this issue and open one specifically for image credit, as it is the only item in this list that continues to be a problem.
