### ISSUE TITLE
Chardonnay Map Data Issues to Fix

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/intertwine#94]
Connections:
- [x] JoP to Heitz connection order backwards (need to reconnect cards)

Fix images for:
- [x] Stony Hill
- [x] 1936 Wente Chardonnay
- [x] Heitz Cellar Chardonnay

**Comment by wrenaria** [comment]
This content is fixed and ready to be re-imported.

**Comment by jrmerz** [comment]
data has been re-imported
