### ISSUE TITLE
JoP Map Data Issues to Fix

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/intertwine#96]
This is a comprehensive list of found data/content issues to fix for the [Judgment of Paris map](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/jop/). All my testing was done in Chrome.

**Data missing or incorrectly mapped:**
- [x] **BUG** [ SEE ISSUE #95 ] Cannot open Pierre Brejoux's info when I click on his dot on the map. If I click on his name in a cluster, then I also cannot activate a different cluster by clicking on it, app locks up.  [[trello](https://trello.com/c/TLDNGtcT/12-pierre-br%C3%A9joux), [map cluster with brejoux](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/jop/cluster/48.8680,2.4150/9/TLD.62t)] 
- [x] Pierre Tari is missing his "Learn More" link ([map](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/jop/person/Wa1OnKCL), [trello](https://trello.com/c/Wa1OnKCL/18-pierre-tari))
- [x] Château Mouton Rothschild Learn More titles are displayed incorrectly as single letters ([map](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/jop/place/a4xqyd1U), [trello](https://trello.com/c/a4xqyd1U/29-ch%C3%A2teau-mouton-rothschild))
- [x] Sometimes wrong image credit is shown or it is not shown at all... Not sure why/how to trigger this. First noticed on Clos Du Val ([map](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/jop/place/D37urK0h), [trello](https://trello.com/c/D37urK0h/27-clos-du-val)). JM - Image credit for this card seems wrong, not a trello list

**Trello subjects missing from the map:**
- [x] Warren Winiarski ([map](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/jop/person/Nn9iS1kw), [trello](https://trello.com/c/Nn9iS1kw/23-warren-winiarski)) -- was in wrong location in map, google map link now fixed

**Trello data / image mistakes (Kimmy will fix):**
- [x] Aubert - fix image crop ([map](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/jop/person/19H6O8s0), [trello](https://trello.com/c/19H6O8s0/20-aubert-de-villaine))
- [x] Odette - fix image crop ([map](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/jop/person/62tsFHXQ), [trello](https://trello.com/c/62tsFHXQ/15-odette-kahn))
- [x] Domaine Leflaive - fix image crop ([map](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/jop/place/iJDHzQxd), [trello](https://trello.com/c/iJDHzQxd/45-domaine-leflaive))
- [x]  Add "produced by" connection to Montelena Chardonnay so its the same set of connections as the other winner Stag's Leap ([map](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/jop/object/Obny8Rpq), [trello](https://trello.com/c/Obny8Rpq/35-1973-chateau-montelena-chardonnay))

**Comment by jrmerz** [comment]
@qjhart the `Château Mouton Rothschild` data issue was partially fixed with commit 582dbb3 whoever, while the `relatedLink` has both urls, the `relatedLinkText` only has one text label. [trello link](https://trello.com/c/a4xqyd1U/29-ch%C3%A2teau-mouton-rothschild)

**Comment by jrmerz** [comment]
@wrenaria this trello card seems like the image credit is not a list: https://trello.com/c/D37urK0h/27-clos-du-val.  Can you fix?

**Comment by wrenaria** [comment]
@jrmerz Fixed.

**Comment by wrenaria** [comment]
@jrmerz Now Château Mouton Rothschild shows just one "Learn More" link title and a blank for the other. But everything else in the list appears to be working as expected.

**Comment by qjhart** [comment]
@jrmerz This looks like an error in the trello2Moment schema:

we have:

```ttl
    schema:relatedLink <https://www.chateau-mouton-rothschild.com/>;
    schema:relatedLinkText "Château Mouton Rothschild";
    schema:relatedLink <https://en.wikipedia.org/wiki/Ch%C3%A2teau_Mouton_Rothschild>;
    schema:relatedLinkText "Château Mouton Rothschild";
```
But in that case, you really don't know which text goes with which link.  schema.org isn't really any help, since a schema:realtedLink is supposed to just be related link, otherwise I'd suggest something like: 

```ttl
    schema:relatedLink [  schema:url <https://www.chateau-mouton-rothschild.com/>;
                                       schema:name "Château Mouton Rothschild"];
    schema:relatedLink [ schema:url <https://en.wikipedia.org/wiki/Ch%C3%A2teau_Mouton_Rothschild>;
    schema:name "Château Mouton Rothschild"; ];
```
```

**Comment by qjhart** [comment]
@jrmerz see : https://github.com/ucd-library/trello2moment/pull/55
